#!/usr/bin/env bash

# Sends a variety of test notifications to manually verify that notifications
# are rendering correctly with different combinations of icons and images.
#
# Generated by Claude (claude-opus-4-5-20251101)

set -e

# Find random icon paths from XDG_DATA_DIRS
IFS=':' read -ra DATA_DIRS <<< "${XDG_DATA_DIRS:-/usr/share:/usr/local/share}"

ICON_DIRS=()
for dir in "${DATA_DIRS[@]}"; do
  [[ -d "$dir/icons" ]] && ICON_DIRS+=("$dir/icons")
done

if [[ ${#ICON_DIRS[@]} -eq 0 ]]; then
  echo "Error: No icon directories found in XDG_DATA_DIRS" >&2
  exit 1
fi

# Randomly pick image paths and icon names (stream through shuf for performance)
echo "Picking random icons from ${#ICON_DIRS[@]} icon directories..."
mapfile -t IMAGE_PATHS < <(find -L "${ICON_DIRS[@]}" -type f \( -name "*.png" -o -name "*.svg" \) 2>/dev/null | shuf -n4)

if [[ ${#IMAGE_PATHS[@]} -lt 2 ]]; then
  echo "Error: Could not find enough icon files" >&2
  exit 1
fi

IMAGE_PATH_1="${IMAGE_PATHS[0]}"
IMAGE_PATH_2="${IMAGE_PATHS[1]}"
ICON_NAME_1=$(basename "${IMAGE_PATHS[2]}" | sed 's/\.\(png\|svg\)$//')
ICON_NAME_2=$(basename "${IMAGE_PATHS[3]}" | sed 's/\.\(png\|svg\)$//')

echo "Using:"
echo "  IMAGE_PATH_1: $IMAGE_PATH_1"
echo "  IMAGE_PATH_2: $IMAGE_PATH_2"
echo "  ICON_NAME_1: $ICON_NAME_1"
echo "  ICON_NAME_2: $ICON_NAME_2"
echo

echo "Sending notifications:"

# Both image-path and app icon
notify-send -i "$ICON_NAME_1" "Path + Icon" "image-path is a path, app icon is an icon name" \
  -h string:image-path:"$IMAGE_PATH_1"

notify-send -i "$IMAGE_PATH_1" "Path + Path" "Both are absolute paths" \
  -h string:image-path:"$IMAGE_PATH_2"

notify-send -i "$ICON_NAME_1" "Icon + Icon" "Both are icon names" \
  -h string:image-path:"$ICON_NAME_2"

notify-send -i "$IMAGE_PATH_1" "Icon + Path" "image-path is an icon name, app icon is a path" \
  -h string:image-path:"$ICON_NAME_1"

# Only image-path
notify-send "Image Path Only" "image-path is a path, no app icon" \
  -h string:image-path:"$IMAGE_PATH_1"

notify-send "Icon Name Only" "image-path is an icon name, no app icon" \
  -h string:image-path:"$ICON_NAME_1"

# Only app icon
notify-send -i "$ICON_NAME_1" "Icon Only" "App icon is an icon name, no image-path"

notify-send -i "$IMAGE_PATH_1" "Path Only" "App icon is a path, no image-path"

# Neither
notify-send "No Images" "No icon, no image-path"

# Invalid paths
notify-send -i "$ICON_NAME_1" "Invalid Path + Valid Icon" "image-path doesn't exist, app icon is valid" \
  -h string:image-path:/nonexistent/path/to/image.png

notify-send -i /nonexistent/path/to/icon.png "Valid Path + Invalid Path" "image-path is valid, app icon path doesn't exist" \
  -h string:image-path:"$IMAGE_PATH_1"

notify-send -i nonexistent-icon-name "Valid Path + Invalid Icon" "image-path is valid, app icon name doesn't exist" \
  -h string:image-path:"$IMAGE_PATH_1"

notify-send "Invalid Path Only" "image-path doesn't exist, no app icon" \
  -h string:image-path:/nonexistent/path/to/image.png

notify-send "Invalid Icon Only" "image-path is invalid icon name, no app icon" \
  -h string:image-path:nonexistent-icon-name

notify-send -i /nonexistent/path/to/icon.png "Invalid Path Only (app icon)" "No image-path, app icon path doesn't exist"

notify-send -i nonexistent-icon-name "Invalid Icon Only (app icon)" "No image-path, app icon name doesn't exist"

notify-send -i /nonexistent/path/to/icon.png "Both Invalid Paths" "Both paths don't exist" \
  -h string:image-path:/another/nonexistent/path.png

notify-send -i nonexistent-icon-name "Both Invalid Icons" "Both icon names don't exist" \
  -h string:image-path:another-nonexistent-icon

echo "Done!"
